apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-pod
  labels:
    app: nginx-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
     app: nginx-deploy
    matchExpressions:
     - key: env
       operator: In
       values:
         - dev
  strategy:
   rollingUpdate:
     maxSurge: 50%
     maxUnavailable: 50%
   type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-deploy
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          #requests:
          #memory: "64Mi"
          #cpu: "250m"
         limits:
          memory: "128Mi"
          cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
 name: rs-svc
spec: 
 selector:
   app: nginx
 type: NodePort
 ports:
  - name: http
    port: 80
    targetPort: 80
