apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Technical-Guftgu wow wow; sleep 5 ; done"]
      evn:
      - name: MYNAME
        value: vidya
    - name: c2
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder how are you; sleep 5 ; done"]
    - name: c3
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Thankyouuuuuuu; sleep 5 ; done"]
