apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: demo-ns
  labels:
    volume: test
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: demo-ns
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv2
  namespace: demo-ns
  labels:
    volume: test2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"
